
#define CONFIG_SERIAL_BAUD_RATE 			9600

/* OSCILOSCOPE */
#define CONFIG_OSCILOSCOPE_INPUT_PIN			A0
#define CONFIG_OSCILOSCOPE_VERSION			"0.23"
#define CONFIG_OSCILOSCOPE_SCREEN_WIDTH			159
#define CONFIG_OSCILOSCOPE_SCREEN_HEIGHT		50
#define CONFIG_OSCILOSCOPE_SCREEN_REAL_HEIGHT		127	
#define CONFIG_OSCILOSCOPE_SCREEN_MAX_OFFSET		93
#define CONFIG_OSCILOSCOPE_SCREEN_MIN_OFFSET		43
#define CONFIG_OSCILOSCOPE_CHUNK_SIZE			159

/* TFT SCREEN CONFIGS */
#define CONFIG_TFT_DC 					9
#define CONFIG_TFT_RST 					8
#define CONFIG_TFT_CS 					10

/* BUTTON */
#define CONFIG_BUTTON_CALC_INTERRUPT			2
